[package]
name = "rclock"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = "4.5.48"
ratatui = "0.29.0"
serde = {version="1.0.227", features=["derive"]}
toml = "0.9.7"
tui-big-text = "0.7.1"
